language: node_js
dist: trusty
node_js:
  - 8
before_install:
  - sudo apt-get update && sudo apt-get install -y --force-yes automake autoconf pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev libgmp-dev make g++
